import esbuild from 'esbuild';
import process from 'process';
import fs from 'node:fs';
import path from 'node:path';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 构建产物统一输出到 output/ 目录（不污染项目根目录）
const outdir = 'output';

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outdir, 'main.js'),
	minify: prod,
});

if (prod) {
	await context.rebuild();

	// 复制插件安装所需的静态资源到 output/，使 output/ 成为可直接安装的插件包
	fs.mkdirSync(outdir, { recursive: true });
	for (const file of ['manifest.json', 'styles.css']) {
		fs.copyFileSync(file, path.join(outdir, file));
	}

	process.exit(0);
} else {
	await context.watch();
}
